export const categories = [
  {
    id : 1,
    img : "/images/ontap.jpg",
    title :"자판기 원두", 
  },
  {
    id : 2,
    img : "/images/categorie_2.jpg",
    title :"커피원두", 
  },
  {
    id : 3,
    img : "/images/categorie_2.jpg",
    title :"아몰랑", 
  },
]

export const product_data = [
  {
    id: 1,
    title: "자판기용 원두 1kg",
    desc: "자판기에서 사용하기 적합한 원두입니다.",
    img: "/images/ontap.jpg",
    categories: ["중고커피자판기"],
    price: 15000,
    inStock: true,
  },
  {
    id: 2,
    title: "콜롬비아 원두 500g",
    desc: "콜롬비아에서 직수입한 신선한 원두입니다.",
    img: "/images/categorie_2.jpg",
    categories: ["중고커피자판기"],
    price: 20000,
    inStock: true,
  },
  {
    id: 3,
    title: "에티오피아 예가체프 1kg",
    desc: "에티오피아 예가체프 지역에서 생산된 스페셜티 원두입니다.",
    img: "/images/machine.jpg",
    categories: ["커피원두"],
    price: 35000,
    inStock: false,
  },
  {
    id: 4,
    title: "디카페인 원두 500g",
    desc: "카페인을 제거한 디카페인 원두입니다.",
    img: "/images/machine.jpg",
    categories: ["종이컵"],
    price: 18000,
    inStock: true,
  },
  {
    id: 5,
    title: "브라질 산토스 1kg",
    desc: "브라질 산토스 지역에서 생산된 고품질 원두입니다.",
    img: "/images/categorie_2.jpg",
    categories: ["커피원두"],
    price: 25000,
    inStock: true,
  },
  {
    id: 6,
    title: "케냐 AA 1kg",
    desc: "케냐 AA 등급의 프리미엄 원두입니다.",
    img: "/images/categorie_2.jpg",
    categories: ["물수건"],
    price: 40000,
    inStock: false,
  },
  {
    id: 7,
    title: "과테말라 안티구아 500g",
    desc: "과테말라 안티구아 지역에서 생산된 고급 원두입니다.",
    img: "/images/categorie_2.jpg",
    categories: ["일회용용기"],
    price: 22000,
    inStock: true,
  },
  {
    id: 8,
    title: "인도네시아 만델링 1kg",
    desc: "인도네시아 만델링 지역에서 생산된 진한 풍미의 원두입니다.",
    img: "/images/categorie_2.jpg",
    categories: ["커피자판기"],
    price: 30000,
    inStock: true,
  },
];